import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'follow_up_entry_page.dart';
import 'follow_up_repository.dart';
import 'models/follow_up.dart';
import 'services/waiting_for_response_service.dart';

class FollowUpOfficePage extends StatefulWidget {
  const FollowUpOfficePage({super.key, this.repository = const FollowUpRepository()});
  final FollowUpRepository repository;
  @override State<FollowUpOfficePage> createState() => _FollowUpOfficePageState();
}

class _FollowUpOfficePageState extends State<FollowUpOfficePage> {
  static const _storeKey='arvin.tasks';
  static const _waitingService=WaitingForResponseService();
  bool _loading=true, _saving=false, _showFutureOnly=false, _showWaitingOnly=false;
  List<_TaskOption> _tasks=const[]; List<_FollowUpRow> _rows=const[];
  @override void initState(){super.initState();_load();}
  Future<void> _load() async { final prefs=await SharedPreferences.getInstance(); final raw=prefs.getString(_storeKey); final tasks=<_TaskOption>[], rows=<_FollowUpRow>[]; if(raw!=null&&raw.isNotEmpty){try{for(final item in jsonDecode(raw) as List<dynamic>){final task=Map<String,dynamic>.from(item as Map);final id=task['id'] as String? ??'',title=task['title'] as String? ??'';if(id.isNotEmpty)tasks.add(_TaskOption(id:id,title:title.trim().isEmpty?'بدون عنوان':title));final history=task['followUps'];if(history is List&&history.isNotEmpty){for(final entry in history){try{rows.add(_FollowUpRow(taskId:id,taskTitle:title,followUp:FollowUp.fromJson(Map<String,dynamic>.from(entry as Map))));}catch(_){}}}else{final legacy=DateTime.tryParse(task['followUpDate'] as String? ??'');if(legacy!=null)rows.add(_FollowUpRow(taskId:id,taskTitle:title,followUp:FollowUp(id:legacy.microsecondsSinceEpoch.toString(),dateTime:legacy,note:'پیگیری قدیمی مهاجرت‌شده')));}}}catch(_){}} rows.sort((a,b)=>b.dateTime.compareTo(a.dateTime));if(!mounted)return;setState((){_tasks=tasks;_rows=rows;_loading=false;});}
  Future<_TaskOption?> _selectTask() async {if(_tasks.isEmpty){_showMessage('ابتدا یک کار ثبت کنید');return null;}if(_tasks.length==1)return _tasks.single;return showDialog<_TaskOption>(context:context,builder:(c)=>SimpleDialog(title:const Text('انتخاب کار'),children:[for(final task in _tasks)SimpleDialogOption(onPressed:()=>Navigator.of(c).pop(task),child:Row(children:[const Icon(Icons.task_alt_outlined),const SizedBox(width:10),Expanded(child:Text(task.title))]))]));}
  Future<void> _addFollowUp() async {final task=await _selectTask();if(task==null||!mounted)return;final followUp=await Navigator.of(context).push<FollowUp>(MaterialPageRoute(builder:(_)=>const FollowUpEntryPage()));if(followUp==null||!mounted)return;setState(()=>_saving=true);try{await widget.repository.add(task.id,followUp);await _load();if(mounted)_showMessage('پیگیری برای «${task.title}» ثبت شد');}catch(_){if(mounted)_showMessage('ثبت پیگیری انجام نشد؛ دوباره تلاش کنید');}finally{if(mounted)setState(()=>_saving=false);}}
  Future<void> _editFollowUp(_FollowUpRow row) async {if(row.taskId.isEmpty||!mounted)return;final updated=await Navigator.of(context).push<FollowUp>(MaterialPageRoute(builder:(_)=>FollowUpEntryPage(initialFollowUp:row.followUp)));if(updated==null||!mounted)return;setState(()=>_saving=true);try{await widget.repository.update(row.taskId,updated);await _load();if(mounted)_showMessage('پیگیری «${row.taskTitle}» ویرایش شد');}catch(_){if(mounted)_showMessage('ویرایش پیگیری انجام نشد؛ دوباره تلاش کنید');}finally{if(mounted)setState(()=>_saving=false);}}
  void _showMessage(String message){ScaffoldMessenger.of(context)..hideCurrentSnackBar()..showSnackBar(SnackBar(content:Text(message)));}
  String _digits(String value){const w='0123456789',p='۰۱۲۳۴۵۶۷۸۹';var r=value;for(var i=0;i<w.length;i++){r=r.replaceAll(w[i],p[i]);}return r;}
  String _dateTime(DateTime v)=>'${_digits('${v.year}/${v.month.toString().padLeft(2,'0')}/${v.day.toString().padLeft(2,'0')}')} • ساعت ${_digits('${v.hour.toString().padLeft(2,'0')}:${v.minute.toString().padLeft(2,'0')}')}';
  List<_FollowUpRow> get _waitingRows {final latest=<String,_FollowUpRow>{};for(final row in _rows){if(row.taskId.isEmpty)continue;final current=latest[row.taskId];if(current==null||row.dateTime.isAfter(current.dateTime))latest[row.taskId]=row;}final result=latest.values.where((r)=>_waitingService.isWaitingResult(r.result)).toList();result.sort((a,b)=>b.dateTime.compareTo(a.dateTime));return result;}
  List<_FollowUpRow> get _visibleRows {var rows=_showWaitingOnly?_waitingRows:List<_FollowUpRow>.of(_rows);if(_showFutureOnly){final now=DateTime.now();rows=rows.where((r)=>r.dateTime.isAfter(now)).toList();}return rows;}
  @override Widget build(BuildContext context){final rows=_visibleRows;return Scaffold(appBar:AppBar(title:const Text('دفتر پیگیری'),actions:[IconButton(tooltip:_showWaitingOnly?'نمایش همه پیگیری‌ها':'فقط منتظر پاسخ',onPressed:()=>setState(()=>_showWaitingOnly=!_showWaitingOnly),icon:Icon(_showWaitingOnly?Icons.hourglass_top:Icons.hourglass_top_outlined)),IconButton(tooltip:_showFutureOnly?'نمایش همه':'فقط پیگیری‌های آینده',onPressed:()=>setState(()=>_showFutureOnly=!_showFutureOnly),icon:Icon(_showFutureOnly?Icons.filter_alt:Icons.filter_alt_outlined)),IconButton(onPressed:_saving?null:_load,tooltip:'بازخوانی',icon:const Icon(Icons.refresh))]),body:_loading?const Center(child:CircularProgressIndicator()):rows.isEmpty?Center(child:Text(_showWaitingOnly?'موردی در انتظار پاسخ نیست':_showFutureOnly?'پیگیری آینده‌ای ثبت نشده است':'هنوز پیگیری‌ای ثبت نشده است')):ListView.separated(padding:const EdgeInsets.fromLTRB(16,12,16,96),itemCount:rows.length,separatorBuilder:(_,__)=>const SizedBox(height:10),itemBuilder:(_,i){final row=rows[i],waiting=_waitingService.isWaitingResult(row.result);return Card(child:Padding(padding:const EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[const Icon(Icons.history),const SizedBox(width:8),Expanded(child:Text(row.taskTitle,style:const TextStyle(fontWeight:FontWeight.w700))),if(waiting)const Chip(label:Text('منتظر پاسخ')),IconButton(tooltip:'ویرایش پیگیری',onPressed:_saving||row.taskId.isEmpty?null:()=>_editFollowUp(row),icon:const Icon(Icons.edit_outlined))]),const SizedBox(height:8),Text(_dateTime(row.dateTime)),if(row.note.trim().isNotEmpty)Text(row.note),if(!waiting&&row.result?.trim().isNotEmpty==true)Text('نتیجه: ${row.result}'),if(row.nextFollowUp!=null)Text('پیگیری بعدی: ${_dateTime(row.nextFollowUp!)}')])));}),floatingActionButton:FloatingActionButton.extended(onPressed:_loading||_saving?null:_addFollowUp,icon:const Icon(Icons.add),label:const Text('ثبت پیگیری')));}
}
class _TaskOption{const _TaskOption({required this.id,required this.title});final String id,title;}
class _FollowUpRow{const _FollowUpRow({required this.taskId,required this.taskTitle,required this.followUp});final String taskId,taskTitle;final FollowUp followUp;DateTime get dateTime=>followUp.dateTime;String get note=>followUp.note;String? get result=>followUp.result;DateTime? get nextFollowUp=>followUp.nextFollowUp;}
